### PR TITLE
[FELIX-6407] SCR Logging Fixes and Improvements

### PR DESCRIPTION
**Pull request by amitjoy**
1. Fixed Problem with Log Extension
2. Introduced functionality to disable logging

Fixes [FELIX-6407](https://issues.apache.org/jira/browse/FELIX-6407)

### CODE REVIEW

**Comment by amitjoy** [comment]
@tjwatson @pkriens If you have time, could you guys have a look?

**Comment by pkriens** [comment]
This corrects a problem after I introduced the logging extension to minimize log output and keep it from being mixed up with the bundle's logging. A patch after my change changed this.bundle to bundle but that then referenced the wrong bundle. 

Could this be processed ASAP?

**Comment by amitjoy** [comment]
@tjwatson Just checking on you if you have had a moment to review this MR. I would really appreciate it. Thanks in advance.

**Comment by tjwatson** [comment]
> @tjwatson Just checking on you if you have had a moment to review this MR. I would really appreciate it. Thanks in advance.

I put a comment in https://issues.apache.org/jira/browse/FELIX-6407

**Review by tjwatson — APPROVED** [review]

**Pull request merged**
