### PR TITLE
Introduce configuration options for setting felix shutdown and reload timeout

### PR DESCRIPTION
**Pull request by lucapalano**
JIRA REF: [FELIX-6356](https://issues.apache.org/jira/browse/FELIX-6356)

### CODE REVIEW

**Comment by cziegeler** [comment]
@lucapalano Thanks for your patch and sorry for the very late response.
The OsgiManager class has already support for configuration admin (through registering a ManagedService). I think your patch can be simplified, if it just leverages OsgiManager.getDefaultConfiguration

**Comment by lucapalano** [comment]
Hi @cziegeler,

Thank you for your feedback about. I pushed new commits trying to simplify the previous one.

I'll look forward for your feedback.

Best regards,
Luca

**Comment by cziegeler** [comment]
@lucapalano Thanks again, looks good, but :) by looking at your PR I realized that there is no good way to pass down the configuration from the OsgiManager to a plugin.
I think we could make this easier, if the OsgiManager would simply add the configuration as a request attribute (similar to the others here: https://github.com/apache/felix-dev/blob/master/webconsole/src/main/java/org/apache/felix/webconsole/internal/servlet/OsgiManager.java#L594) before calling the plugin. This would remove the need for all of the (static) managed service/configuration handling

**Comment by lucapalano** [comment]
@cziegeler I see your point. I made it more simple by using, as you suggested, the "request" parameter. "shutdown" and "reload" timeouts attributes are set for the "VMstat" plugin only.

**Comment by cziegeler** [comment]
@lucapalano Awesome, thank you - how about you always just set the full configuration map as an attribute for every plugin - that's not breaking any plugin. But then we don't have a hard dependency from the OsgiManager to the VMstat plugin - and the VMstat plugin just picks whatever it needs from the configuration map?

**Comment by lucapalano** [comment]
@cziegeler now, shutdown and reload timeouts can be accessed via `OsgiManager.PROP_SHUTDOWN_TIMEOUT` and `OsgiManager.PROP_RELOAD_TIMEOUT` configuration props.

The configuration params can be always set, in the webconsole configuration file, by using the props:
- felix.webconsole.shutdown.timeout (OsgiManager.FRAMEWORK_SHUTDOWN_TIMEOUT);
- felix.webconsole.reload.timeout (OsgiManager.FRAMEWORK_RELOAD_TIMEOUT);

**Review by cziegeler — APPROVED** [review]

**Comment by cziegeler** [comment]
@lucapalano Thanks for all the work and sorry for asking for all these changes.

**Pull request merged**
