### PR TITLE
Add github verification for SCR

### PR DESCRIPTION
**Pull request by laeubi**
This adds a github verification workflow for the scr component of felix dev.

I created an example PR how it would looks like after the merge here:
- https://github.com/laeubi/felix-dev/pull/3

FYI @tjwatson @stbischof  I think this should be merged first as it does not require any changes to the code itself to make it run, once we have this we can rebase
- https://github.com/apache/felix-dev/pull/320
- https://github.com/apache/felix-dev/pull/301

on this and further enhance it.

### CODE REVIEW

**Comment by stbischof** [comment]
@tjwatson would it be okay if a merge in felix?

**Comment by tjwatson** [comment]
> @tjwatson would it be okay if a merge in felix?
> 
> I have the rights. But maybe there are some more rules.

It is fine with me to merge.  Please merge if you think it is ready.  Although it will not do anything until we get the repo enabled for actions.

**Comment by laeubi** [comment]
Currently the test parser complains about to large xml data:
 https://github.com/laeubi/felix-dev/pull/3/checks?check_run_id=25087687495

we could either keep this, or I disable the processing of the test files for now or as it only affects the integration test, disable only upload of integration tests...

**Comment by stbischof** [comment]
just upload and no publish

why do you use "stCarolas/setup-maven" and noch the default actions?

**Comment by paulrutter** [comment]
The default actions don't let you specify a maven version.

**Comment by stbischof** [comment]
and what feature has 3.9.6 that we need?

**Comment by laeubi** [comment]
> just upload and no publish
> 
> why do you use "stCarolas/setup-maven" and noch the default actions?

What do you mean by default actions?

One can't tell for sure what the runner have installed (java+maven version) and it might even change or differ between os so for me its good "style" to install wanted java version and wanted maven version.

> and what feature has 3.9.6 that we need?

I don't think there is any certain "feature" just to control what is used as otherwhise it might give surprising results.

**Comment by laeubi** [comment]
> just upload and no publish

done

**Pull request merged**
