### PR TITLE
FELIX-6547 bump bndlib to 6.3.1. This fixes invalid osgi.ee Require-Capability generation

### PR DESCRIPTION
**Pull request by cdietrich**
FELIX-6547 bump bndlib to 6.3.1. This fixes invalid osgi.ee Require-Capability generation

### CODE REVIEW

**Comment by iloveeclipse** [comment]
@tjwatson : see https://github.com/eclipse-pde/eclipse.pde/issues/130

**Comment by laeubi** [comment]
Just in case you don't want to wait, maybe the ebr-recipes project might to migrate to the bnd-maven-plugin in the meantime.

**Comment by iloveeclipse** [comment]
@prangish, @enapps-enorman, @cziegeler , anyone else with commit rights: can we please review this change?

**Review by laeubi — APPROVED** [review]
Looks good!

**Comment by rotty3000** [comment]
thanks for the PR :)

**Comment by cdietrich** [comment]
thx for merging. is there already an eta or release plan for the 5.1.7 release

**Comment by laeubi** [comment]
Copied from the mailing list:

> **[VOTE] Release Felix maven-bundle-plugin-5.1.7**
>
> Hi,
> 
> We fixed 2 issues in this release of maven-bundle-plugin-5.1.7
> 
> Changelog:
> https://issues.apache.org/jira/browse/FELIX-6547?jql=project%20%3D%20FELIX%20AND%20fixVersion%20%3D%20maven-bundle-plugin-5.1.7
> 
> Staging repository:
> https://repository.apache.org/content/repositories/orgapachefelix-1435
> 
> Please vote to approve this release:
> 
> [ ] +1 Approve the release
> [ ] -1 Veto the release (please provide specific comments)
> 
> This vote will be open for 72 hours.
> 
> Ray

**Pull request merged**
