### PR TITLE
FELIX-6705 Upgrade to jetty 12.0.10 

### PR DESCRIPTION
**Pull request by paulrutter**
https://issues.apache.org/jira/browse/FELIX-6705

### CODE REVIEW

**Comment by stbischof** [comment]
We may should use a constant for the version in the IT classes .

**Comment by paulrutter** [comment]
Yes, i will adjust that

**Comment by paulrutter** [comment]
Changed to draft, as the jetty12 unit tests fail after moving to 12.0.9.

**Comment by paulrutter** [comment]
I had to add the new https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-ee/12.0.9 bundle to the test.
I also added it to the `Export-Package`.

**Comment by paulrutter** [comment]
Jetty 12.0.10 is incoming, will adjust the PR.
I ran it already with a custom build because 12.0.8 seems to have an issue causing a deadlock in some edge cases.

**Pull request merged**
