### PR TITLE
FELIX-6602 sort resources and exported packages

### PR DESCRIPTION
**Pull request by hboutemy**
fixes https://issues.apache.org/jira/browse/FELIX-6602

tested on a few projects (mybatis-3, activemq-artemis), using disorderfs to make sure that these 2 changes fix last remaining issues

### CODE REVIEW

**Comment by hboutemy** [comment]
@jbonofre any problem to merge and release?

**Comment by jbonofre** [comment]
No problem, I will do that. Sorry for the delay.

**Comment by hboutemy** [comment]
no worries, I hope this one will really be the last for Reproducible Builds, after FELIX-6304 (5.1.1), FELIX-6404 (5.1.3), FELIX-6495 (5.1.4), FELIX-6496 (5.1.5)

**Comment by hboutemy** [comment]
Hi @jbonofre , any time to merge and release, please?

**Comment by hboutemy** [comment]
@jbonofre please?

**Comment by jbonofre** [comment]
Yes. Sorry I forgot. I will move forward on this one.

**Review by jbonofre — APPROVED** [review]

**Comment by hboutemy** [comment]
thank you

**Pull request merged**
