### PR TITLE
Upgrade Apache Felix to Jakarta Servlet API 6.x (milestone 2)

### PR DESCRIPTION
**Pull request by ideas-into-software**
As initiated and discussed via https://issues.apache.org/jira/browse/FELIX-6612, final milestone of migrating 30 Apache Felix modules to Jakarta Servlet API 6.0 (https://jakarta.ee/specifications/servlet/6.0/) and Whiteboard Specification for Jakarta™ Servlet (https://docs.osgi.org/specification/osgi.cmpn/8.1.0/service.servlet.html) is now complete. A separate branch and pull request for Jakarta Servlet API 5.0 was made 3 days ago: https://github.com/apache/felix-dev/pull/217

Following modules were affected, including Apache Felix HTTP, Apache Felix Webconsole, Apache Felix Healthcheck, as well as Apache Felix Webconsole plugins and Apache Felix Parent:
 - `felix-parent`
 - `org.apache.felix.healthcheck.core`
 - `org.apache.felix.healthcheck.webconsoleplugin`
 - `org.apache.felix.http`
 - `org.apache.felix.http.base`
 - `org.apache.felix.http.bridge`
 - `org.apache.felix.http.inventoryprinter`
 - `org.apache.felix.http.itest`
 - `org.apache.felix.http.jetty`
 - `org.apache.felix.http.parent`
 - `org.apache.felix.http.proxy`
 - `org.apache.felix.http.samples.whiteboard`
 - `org.apache.felix.http.servlet-api`
 - `org.apache.felix.http.sslfilter`
 - `org.apache.felix.http.webconsoleplugin`
 - `org.apache.felix.inventory`
 - `org.apache.felix.webconsole`
 - `org.apache.felix.webconsole.plugins.deppack`
 - `org.apache.felix.webconsole.plugins.ds`
 - `org.apache.felix.webconsole.plugins.event`
 - `org.apache.felix.webconsole.plugins.gogo`
 - `org.apache.felix.webconsole.plugins.memoryusage`
 - `org.apache.felix.webconsole.plugins.metatype`
 - `org.apache.felix.webconsole.plugins.obr`
 - `org.apache.felix.webconsole.plugins.packageadmin`
 - `org.apache.felix.webconsole.plugins.scriptconsole`
 - `org.apache.felix.webconsole.plugins.shell`
 - `org.apache.felix.webconsole.plugins.subsystems`
 - `org.apache.felix.webconsole.plugins.upnp`
- `org.apache.felix.webconsole.plugins.useradmin`

All unit tests and integration tests pass, with one exception: `org.apache.felix.webconsole.plugins.scriptconsole` – here, all unit tests work, but Pax Exam Integration tests fail with error "Problem starting test container" due to old dependencies / transitive dependencies having "http://repo1.maven.org/maven2/" Maven repository defined (instead of HTTPS). I do know how to fix that problem, however, since I did not work with Pax Exam prior to this project, I will leave this to someone more experienced with Pax Exam.

Since I cannot create new branches on https://github.com/apache/felix-dev, please create a dedicated branch (e.g. `jakarta-servlet-6-x`) – due to reasons mentioned in https://issues.apache.org/jira/browse/FELIX-6612 discussion, the `jakarta-servlet-6-x` should be kept separate from `master`.. unless that decision changed in the meantime.

Please note that upgrade of external dependencies was also taken care of, i.e.:
 - Upgrade of `org.osgi.service.servlet` to support Jakarta Servlet API 6.x: https://github.com/osgi/osgi/pull/611
 - Upgrade of `commons-fileupload2-jakarta` to support Jakarta Servlet API 6.x: https://github.com/apache/commons-fileupload/pull/232

### CODE REVIEW

**Comment by ideas-into-software** [comment]
@cziegeler 

As per your request, I switched this PR to https://github.com/apache/felix-dev/tree/jakarta-servlet-6 branch you created.
I also took care of verifying upgraded artifacts (Apache Felix HTTP, Apache Felix Inventory as well as Apache Felix Web Console and plugins) as part of an actual project. 

The tests apparently do not have sufficient coverage, because even though all tests passed (see my earlier comment, https://github.com/apache/felix-dev/pull/218#issue-1828103395, for more info about tests and the `org.apache.felix.webconsole.plugins.scriptconsole` exception), there were multiple issues which came up when integrating these artifacts into actual project. 

All those issues were fixed and that’s what those latest commits in this PR address, i.e. fixes for issues with Felix Web Console, Web Console plugins & related, including propagation of custom configuration, missing Whiteboard service parameters resulting in plugins not being registered properly, path resolution issues, etc.

As mentioned, those cases are not covered by any of the existing tests and were discovered during exploratory testing as part of an actual project. That project is https://github.com/geckoprojects-org/org.gecko.graphql and in this PR (and its commits) you will find more details: https://github.com/geckoprojects-org/org.gecko.graphql/pull/8

Just in case this is not clear (and I do not mean you, @cziegeler): since there are multiple artifacts from 3 different projects (Apache Felix being one of those 3), such must be first build and installed into local Maven repository before being used in a project, until they’re officially released, i.e. :
- `org.apache.commons:commons-fileupload2-core:2.0.0-M3-SNAPSHOT` and `org.apache.commons:commons-fileupload2-jakarta-servlet6:2.0.0-M3-SNAPSHOT` artifacts – until they’re released, you can build and install those into your local Maven repository from https://github.com/ideas-into-software/commons-fileupload/tree/osgi-enhancements branch
- `org.osgi:org.osgi.service.servlet:3.0.0-SNAPSHOT` – until it’s released, build and install it from https://github.com/ideas-into-software/osgi/tree/requirements/597 branch
- upgraded Apache Felix artifacts – until it’s released, build and install it from https://github.com/DataInMotion/felix-dev/tree/jakarta-servlet-6-x branch (soon https://github.com/apache/felix-dev/tree/jakarta-servlet-6 branch)

I am not sure when you or Felix team will conduct review of code in this PR, but I would like to ask for clarification regarding creation of pattern matcher dependent on service ID of handler used (previously `HttpServiceFactory.HTTP_SERVICE_CONTEXT_SERVICE_ID`) – prior to this upgrade/refactor, such was checked in `org.apache.felix.http.base.internal.registry.PathResolverFactory.createPatternMatcher(ServletHandler, String)` and instance of `org.apache.felix.http.base.internal.registry.PathResolverFactory.ExactAndPathMatcher.ExactAndPathMatcher(ServletHandler, String)` created; should such exceptional case still exist, e.g. `org.apache.felix.http.base.internal.registry.PathResolverFactory.ExactAndPathMatcher.ExactAndPathMatcher(ServletHandler, String)` pattern matcher created if given handler is for default context ? 

Also, some improvement suggestions:
 - add tests to cover cases which were only discovered during exploratory testing (and hence these new commits);
 - consistent registration of internal / external web console plugins – currently, those are registered in four different ways, including via `org.apache.felix.webconsole.SimpleWebConsolePlugin.register(BundleContext)`, as well as via their activators (`org.apache.felix.webconsole.plugins.event.internal.Activator`), constructors (`org.apache.felix.webconsole.plugins.scriptconsole.internal.ScriptConsolePlugin`, `org.apache.felix.inventory.impl.InventoryPrinterManagerImpl.InventoryPrinterManagerImpl(BundleContext)`) and specialized methods (`org.apache.felix.inventory.impl.InventoryPrinterAdapter.registerConsole(BundleContext, InventoryPrinterManagerImpl)`;
  - refactor Apache Felix Inventory Web Console plugin to Apache Felix Webconsole as internal plugin – currently, class hierarchy and constants are duplicated as to avoid cyclic dependencies, but this looks like a candidate for another internal Web Console plugin, instead of being maintained separately;

I will appreciate providing improvement suggestions for any of the new / refactored code in this PR, where needed.

**Review by cziegeler — APPROVED** [review]

**Comment by cziegeler** [comment]
@ideas-into-software Thanks for the updated PR and description; In general it looks good to me; however there is a conflict that needs to be resolved before applying

**Comment by ideas-into-software** [comment]
@cziegeler 

Conflicting file was updated, so now it's all green for merge.

Now that PR is approved, and conflict resolved, can PR be merged and can JIRA issue (https://issues.apache.org/jira/browse/FELIX-6612) be marked as resolved, or do you wish to conduct code review, including follow up on question I asked in previous comment (https://github.com/apache/felix-dev/pull/218#issuecomment-1672266266), regarding `org.apache.felix.http.base.internal.registry.PathResolverFactory.createPatternMatcher(ServletHandler, String)`?

I already merged latest from `master` branch on August 9th, before submitting this PR, but new commits are merged to `master` frequently, so unfortunately new conflicts may arise, as you know, depending on how long these next steps take.

**Comment by cziegeler** [comment]
Thanks for updating the PR; there will be a constant battle of keeping the branches in sync; but for the time being I think we don't have any other option. So changes to the main branch need to be ported to the jakarta 6 branch as well.
For any improvements or changes on the existing modules, if these don't break current usage, its best to apply those to the main branch first; avoiding that the code drifts too far apart
But I think all of that should be handled in separate issues to make tracking easier.

**Comment by rakeshk15** [comment]
@cziegeler I have not seen the latest code here but will this jakarta-servlet-6 branch have the javax/jakarta wrappers approach which you did earlier or is this all new for Servlet 6 only.

**Comment by cziegeler** [comment]
@rakeshk15 No wrappers, as Servlet 6 is not fully compatible to Servlet 5 (and earlier). We'll continue to have the wrappers with the Servlet 5 implementation on the main branch

**Comment by rakeshk15** [comment]
Understood, thanks for clarification.

**Pull request merged**
