### PR TITLE
FELIX-6669 - proper detection of string property & comment boundaries…

### PR DESCRIPTION
**Pull request by DominikSuess**
… to avoid mixing and false positive and false negative stripping

### CODE REVIEW

**Comment by DominikSuess** [comment]
@rombert  @cziegeler  @bosschaert  - as statet in the ticket I missed valid scenarios that were not covered by unit tests so far and being too consumed with the newline handling I missed that I dropped the corresponding handling of the original logic - the flow should now be better readable and properly handle string property and comment detection and prevents the logic of the other branch to act until finding and processing the corresponding end token

**Comment by cziegeler** [comment]
@DominikSuess Do you handle the case where the string value contains a quote? ("\"" ?)

**Comment by rombert** [comment]
Thanks for the PR @DominikSuess , I have merged it.

**Comment by amitjoy** [comment]
@DominikSuess @cziegeler Would this fix https://issues.apache.org/jira/browse/FELIX-6670?

**Comment by rombert** [comment]
@amitjoy - I have concluded the release vote for felix cm.json 2.0.4 but I am waiting on a PMC member to promote it. Can you try out https://repository.apache.org/content/repositories/orgapachefelix-1480/ and see if it fixes your problem?

**Comment by amitjoy** [comment]
@rombert Just verified. Works perfectly 👍

**Comment by rombert** [comment]
Great, thanks for confirming @amitjoy !

**Pull request merged**
