### PR TITLE
Convert to Interface without methods - FELIX-6238

### PR DESCRIPTION
**Pull request by stbischof**
https://issues.apache.org/jira/browse/FELIX-6238

### CODE REVIEW

**Comment by bosschaert** [comment]
LGTM

@timothyjward WDYT?

**Comment by timothyjward** [comment]
This method has always been a bit odd to read - it still seems odd to check that the methods returned by the interface are defined by the interface. 

As for the change, it looks correct, but would it be better to assign the output of `getMethods` to a local variable before the for loop so we don’t need to get the array twice?

**Comment by bosschaert** [comment]
@stbischof would you have time to implement the change suggested by @timothyjward ?

**Comment by stbischof** [comment]
@bosschaert sure. tomorrow!

**Comment by stbischof** [comment]
@bosschaert here is the small change.

Do you have any ideas ho to handle this?:
https://issues.apache.org/jira/browse/FELIX-6239

**Pull request merged**
