### PR TITLE
FELIX-6512 : Support for synchronous registration of persistence mana…

### PR DESCRIPTION
**Pull request by rotty3000**
…gers and configuration plugins

Signed-off-by: Raymond Augé <rotty3000@apache.org>

### CODE REVIEW

**Comment by cziegeler** [comment]
@rotty3000  The patch looks good to me - I was wondering whether we need the configuration option? Or in other words, are there cases where sync registration does not work?
TBH I don't recall why I implemented this being async

**Comment by rotty3000** [comment]
@cziegeler right. Could there be a risk in removing the existing behaviour? That was the question I was asking myself. However, if you wish I can certainly simplify this down to removing the async. We've been using it like this for literally years. On the other hand I would not consider our usage an all encompassing one.

**Comment by cziegeler** [comment]
@rotty3000 I'll give it a test with the different Apache Sling launchers where I know this feature is used. I'll report back here

**Comment by cziegeler** [comment]
@rotty3000 I did some tests with Apache Sling and did not run into problem with synchronous registration. So I think we can just switch and remove all code related to async registration.

**Comment by rotty3000** [comment]
@cziegeler please see updated code

**Review by cziegeler — APPROVED** [review]
lgtm, thanks

**Review by Fool256 — APPROVED** [review]

**Review by Fool256 — APPROVED** [review]

**Pull request merged**
